name: Publish Docker image

on:
  push:
    branches: main

jobs:

# From: https://docs.github.com/en/actions/guides/publishing-docker-images
# Using https://github.com/docker/build-push-action/tree/releases/v1
  push_to_registry_v1:
    name: docker-build-push-action:v1
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: addshore/github-actions-docker-push-example/docker-build-push-action
          tags: v1

# Modified From: https://docs.github.com/en/actions/guides/publishing-docker-images
# Using https://github.com/docker/build-push-action
  push_to_registry_v2:
    name: docker-build-push-action:v2
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/addshore/github-actions-docker-push-example/docker-build-push-action:v2