#https://docs.github.com/en/actions/guides/publishing-docker-images
name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registry_v1:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: addshore/github-actions-docker-push-example/docker-build-push-action
          tags: v1